### ISSUE TITLE
scheme文件的常规拓展名是“.ss”

### ISSUE THREAD

**Issue by dou4cc** [guenchi/Raven#20]
你看你这个仓库已经变成SuperCollider语言的了。

**Comment by guenchi** [comment]
因为scheme现在已经分开为r7rs small和r7rs large

我们倡导使用sc （**sc**hme）来表明这个文件是兼容于r7rs large 而不是普通的r7rs small

**Comment by dou4cc** [comment]
可以给个链接吗？scheme有好多拓展名：
- .ss
- .scm
- .sc

想知道它们的区别。

**Comment by guenchi** [comment]
没什么要紧的区别 都是约定俗成 混用也没事

scm 好像用于脚本
ss 用于编译
rkt 用于 racket方言
我们倡导的  sc   R7RS Large
