### ISSUE TITLE
raven can't be run because of License

### ISSUE THREAD

**Issue by rmrfchik** [guenchi/Raven#39]
when running raven 0.3.1: 
```
% raven
/usr/local/bin/raven: 1: /usr/local/bin/raven: Syntax error: ";" unexpected
```
To use raven I have to remove License from raven.sc, so file starts with
`":"; export CHEZSCHEMELIBDIRS=.:lib:/usr/local/lib && export CHEZSCHEMELIBEXTS=.chezscheme.sls::.chezscheme.so:.ss::.so:.sls::.so:.scm::.so:.sch::.so:.sc::.so && exec scheme --script $0 "$@";`

**Comment by rmrfchik** [comment]
No, problem is still here.
I changed ; to ;;;
`# head /usr/local/bin/raven
;;;  MIT License

;;;  Copyright guenchi, chclock (c) 2017-2018 
         
;;;  Permission is hereby granted, free of charge, to any person obtaining a copy
;;;  of this software and associated documentation files (the "Software"), to deal
;;;  in the Software without restriction, including without limitation the rights
;;;  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
;;;  copies of the Software, and to permit persons to whom the Software is
;;;  furnished to do so, subject to the following conditions:

# raven
/usr/local/bin/raven: line 1: syntax error near unexpected token `;;'
/usr/local/bin/raven: line 1: `;;;  MIT License'

`

**Comment by guenchi** [comment]
fixed， thx
