### ISSUE TITLE
raven install core doesn't install all files

### ISSUE THREAD

**Issue by hinkelman** [guenchi/Raven#50]
When I run `raven install core`, I only get `alist.sc`, `exception.sc`, and `string.sc`, but not the other files (e.g., `loop.sc`).

**Comment by guenchi** [comment]
Hi,

the Raven depot has only release 1.0.0 of Core.

the rest files need more test for release, so if you still wish to use it.
Just copy the files

https://github.com/guenchi/Core

to the ./lib/core/


-Louis

Travis Hinkelman <notifications@github.com> 于2019年7月30日周二 下午10:52写道：
