### ISSUE TITLE
chez-stats library submission

### ISSUE THREAD

**Issue by hinkelman** [guenchi/Raven#51]
I've started working on a [Chez Scheme library](https://github.com/hinkelman/chez-stats) for descriptive statistics and generating random variates that I would like to submit for consideration to Raven. I'm a novice Scheme programmer and might be writing non-idiomatic code. Feedback and contributions are welcome. Thanks.

**Comment by guenchi** [comment]
Hi, welcome

**Comment by hinkelman** [comment]
Hi. Can you tell me more about the submission process? Thanks.

**Comment by guenchi** [comment]
I need a project git address (the test set is important).
I will upload it to the central repository after review.

**Comment by hinkelman** [comment]
Oh, sorry, I 'hid' the GitHub link to the project (https://github.com/hinkelman/chez-stats) in my initial comment.

The test set is here: https://github.com/hinkelman/chez-stats/blob/master/tests.ss

I didn't follow the recommended practice of using `.sc` as the file extension because GitHub's Linguist tool was identifying my project as a scala, not scheme, project.

Thanks.

**Comment by guenchi** [comment]
.ss is ok, we use .sc for "engineering strength", "R6RS and R7RS large","Chez Scheme" meaning.

but if you want, just add  1 line "*.sc linguist-language=Scheme" in ".gitattributes" file in your project root. for avoid GitHub tool was identifying your project as a scala.

**Comment by guenchi** [comment]
I'v added chez-stats to raven packages.

thanks very much for your work.
