### ISSUE TITLE
request to update chez-stats on Raven

### ISSUE THREAD

**Issue by hinkelman** [guenchi/Raven#55]
Please test and update the version of [chez-stats](https://github.com/hinkelman/chez-stats) on Raven to the version that is in the master branch of the chez-stats repository. Thanks!

**Comment by hinkelman** [comment]
Following up on this in case it was missed.

**Comment by guenchi** [comment]
0.6.0 is available.

I am working on automating the construction of a central warehouse. As you know the setup-scheme, it will automatically test your changes to the project, simplify the work before uploading to the central repository.

**Comment by hinkelman** [comment]
Thanks!
