### ISSUE TITLE
contributors wanted?

### ISSUE THREAD

**Issue by hinkelman** [guenchi/Raven#56]
I'm a scheme novice, but I would happy to donate some time to the more tedious tasks associated with managing the Raven project (e.g., reviewing documentation, testing functionality, reviewing package submissions, etc.). Please let me know if you see opportunities for me to contribute. Thanks.

**Comment by guenchi** [comment]
Thank you very much for your proposal.  I will contact you when needed.  Or we can discuss using the scheme to write an upload-review-release platform.
