### ISSUE TITLE
update description of chez-stats on ravensc.com

### ISSUE THREAD

**Issue by hinkelman** [guenchi/Raven#61]
Please update the description of chez-stats on ravensc.com from

> This is a statistics library only in a loose sense. More accurately, it is a hodgepodge of procedures that an R programmer thought would be useful when working in Chez Scheme.

to 

> Read/write CSV files, compute descriptive statistics, and generate random variates in Chez Scheme.

Thanks.

**Comment by guenchi** [comment]
ok:)
