### ISSUE TITLE
should use s-expression instead of json

### ISSUE THREAD

**Issue by ChaosEternal** [guenchi/Raven#9]
since this is a scheme package manager, shouldn't s-exps be used?

ChezScheme does not have native json parser, but every implementation of scheme has s-exp parser.

using s-exp even sxml can employ the powerful pattern matching libararies of scheme, which makes life much easier.

**Comment by guenchi** [comment]
We've been hesitating between the s-expression and the json format:
Json has good readability, but the s-expression is the true scheme. It's hard to make a decision.

Until you join the discussion:

So s-expression won!

and thanks for star our project!
